version: "3.9"

services: 

    # build the initial python container with poetry installed
    # run poetry init the poetry add etc to set up the dependancies
    # re-run this if the dependencies change 
    python:
        build: 
            context: .
            target: pydep
        command: tail -f /dev/null
        volumes: 
            - .:/app
    
    # build the initial node container with npm installed
    # run npm init and npm install etc to set up the node dependancies
    # re-run this if the dependencies change 
    node:
        build: 
            context: .
            target: nodedep
        command: tail -f /dev/null
        volumes: 
            - .:/app

    requirements:
        build: 
            context: .
            target: requirements
        command: tail -f /dev/null
        volumes: 
            - .:/app
        depends_on: 
            - python

    app:
        build: 
            context: .
        command: tail -f /dev/null
        volumes: 
            - ./:/app
        ports: 
            - 8000:8000
        depends_on: 
            - requirements
            - db

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./postgresql:/var/lib/postgresql/data