version: "3.9"

services: 

    utils:
        build: 
            context: .
            target: utils-base
        command: tail -f /dev/null
        volumes: 
            - ./:/app
        ports: 
            - 3000:3000

    app:
        build: 
            context: .
        command: tail -f /dev/null
        volumes: 
            - ./:/app
        ports: 
            - 8000:8000
        depends_on: 
            - db

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./postgresql:/var/lib/postgresql/data